# -*- coding: utf-8 -*-
"""fantasy_text_generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PmKsNCB4jK8lpP_Iv1X31xh2bsZx_tVP
"""

!pip install transformers torch

from transformers import GPT2LMHeadModel, GPT2Tokenizer
import torch

# Load model and tokenizer
model_name = "gpt2"
tokenizer = GPT2Tokenizer.from_pretrained(model_name)
model = GPT2LMHeadModel.from_pretrained(model_name)
model.eval()

def generate_text(prompt, max_length=50, temperature=1.0, seed=None):
    if seed is not None:
        torch.manual_seed(seed)

    input_ids = tokenizer.encode(prompt, return_tensors="pt")
    output = model.generate(
        input_ids,
        max_length=max_length,
        temperature=temperature,
        num_return_sequences=1
    )
    return tokenizer.decode(output[0], skip_special_tokens=True)

# Try fantasy quest
print(generate_text("Quest: The villagers need your help to", temperature=0.7, seed=42))

# Try item
print(generate_text("Item: A sword made from", temperature=1.2, seed=101))

# Try character name
print(generate_text("Character Name: Sir", temperature=0.9, seed=12))

with open("outputs.txt", "w") as f:
    for temp in [0.7, 1.0, 1.5]:
        output = generate_text("Item: A bow crafted by elves", temperature=temp)
        f.write(f"Temperature {temp}:\n{output}\n\n")